version: '3.7'
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: main
    ports:
      - 27017:27017

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://db:27017/
    ports:
      - 3000:3000
    depends_on:
      - db
